# Generated by Django 5.1.6 on 2025-02-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_duedate_task_duetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discription',
            new_name='description',
        ),
    ]
